name: subweb

services:
  gateway:
    extends:
      file: compose.common-services.yaml
      service: gateway
    environment:
      SHORT_LINKS_ENABLED: "false"

  subconverter:
    extends:
      file: compose.common-services.yaml
      service: subconverter

volumes:
  subconverter-runtime:

networks:
  subconverter-egress:
    internal: true
