map $http_content_type $short_content_type_allowed {
  default 0;
  '~*^application/json([ \t]*;[ \t]*[A-Za-z0-9_-]+[ \t]*=[ \t]*("[A-Za-z0-9._ -]+"|[A-Za-z0-9._-]+))*[ \t]*$' 1;
  '~*^application/x-www-form-urlencoded([ \t]*;[ \t]*[A-Za-z0-9_-]+[ \t]*=[ \t]*("[A-Za-z0-9._ -]+"|[A-Za-z0-9._-]+))*[ \t]*$' 1;
}
